/* Books, home & kitchen, desk accessories */
export const rawProducts4 = [
  {id:"p_book_01",n:"The AI Revolution",d:"Bestselling book on artificial intelligence transforming industries.",c:"Books",p:599,dc:0,s:40,a:{genre:"technology",language:"english",pages:384},t:"book,technology,ai,revolution,future",cp:"p_book_02,p_book_03",fb:"p_book_02",u:"education,learning,reading,gift",sg:"students,professionals",sc:89},
  {id:"p_book_02",n:"Clean Code",d:"The definitive guide to writing clean, maintainable code.",c:"Books",p:899,dc:0,s:35,a:{genre:"programming",language:"english",pages:524,author:"Robert Martin"},t:"book,programming,clean-code,developer",cp:"p_book_01,p_book_03,p_laptop_01",fb:"p_laptop_01,p_book_03",u:"education,learning,professional",sg:"developers,students",sc:92},
  {id:"p_book_03",n:"Rich Dad Poor Dad",d:"Personal finance book on assets, liabilities and wealth building.",c:"Books",p:699,dc:10,s:0,a:{genre:"finance",language:"english",pages:336,author:"Robert Kiyosaki"},t:"book,finance,money,personal-development",cp:"p_book_01,p_book_02",fb:"p_book_01",u:"education,gift,learning,reading",sg:"everyone,students,youth",sc:90},
  {id:"p_book_04",n:"Atomic Habits",d:"Atomic Habits by James Clear on building good habits and breaking bad ones.",c:"Books",p:549,dc:0,s:28,a:{genre:"self-help",language:"english",pages:320,author:"James Clear"},t:"book,self-help,habits,james-clear",cp:"p_book_01,p_book_03",fb:"p_book_01",u:"education,gift,learning,reading",sg:"everyone,youth,students",sc:91},
  {id:"p_book_05",n:"Deep Work",d:"Deep Work by Cal Newport on focused success in a distracted world.",c:"Books",p:499,dc:0,s:33,a:{genre:"productivity",language:"english",pages:304,author:"Cal Newport"},t:"book,productivity,deep-work,focus",cp:"p_book_01,p_book_02,p_laptop_01",fb:"p_book_02,p_laptop_01",u:"education,professional,learning",sg:"students,professionals,developers",sc:93},
  {id:"p_mug_01",n:"Ceramic Coffee Mug 350ml",d:"Premium ceramic coffee mug with ergonomic handle and matte finish.",c:"Home & Kitchen",p:349,dc:0,s:60,a:{capacity:"350ml",material:"ceramic",color:"white"},t:"mug,coffee,ceramic,white,kitchen,drink",cp:"p_tea_01",fb:"p_tea_01",u:"coffee,tea,daily-use,office",sg:"everyone,coffee-lovers,office",sc:87},
  {id:"p_tea_01",n:"Premium Assam Tea Blend 100g",d:"High-quality Assam black tea blend, strong malty flavor.",c:"Home & Kitchen",p:299,dc:0,s:45,a:{type:"black-tea",origin:"assam",weight:"100g",flavor:"strong-malty"},t:"tea,assam,black-tea,premium,breakfast",cp:"p_mug_01,p_biscuit_01",fb:"p_mug_01,p_biscuit_01",u:"breakfast,morning,tea-time,daily",sg:"everyone,tea-lovers",sc:85},
  {id:"p_biscuit_01",n:"Dark Chocolate Biscuits",d:"Artisanal dark chocolate biscuits with 70% cocoa and sea salt.",c:"Home & Kitchen",p:399,dc:0,s:38,a:{flavor:"dark-chocolate",weight:"200g",cocoa:"70%",texture:"crunchy"},t:"biscuit,chocolate,dark,snack,premium",cp:"p_mug_01,p_tea_01",fb:"p_mug_01,p_tea_01",u:"snacking,evening-tea,gift,daily",sg:"everyone,chocolate-lovers",sc:88},
  {id:"p_bag_charcoal",n:"Charcoal Messenger Bag",d:"Charcoal grey messenger bag with padded laptop compartment.",c:"Accessories",p:1599,dc:0,s:16,a:{color:"charcoal",material:"nylon",size:"15-inch",water_resistant:"yes"},t:"bag,messenger,charcoal,nylon,water-resistant",cp:"p_laptop_01,p_laptop_04",fb:"p_laptop_01,p_mouse_01",u:"student,office,travel,daily",sg:"students,commuters,professionals",sc:91},
  {id:"p_earbuds_pro",n:"Pro Wireless Earbuds",d:"Pro wireless earbuds with ANC, spatial audio, 30h battery.",c:"Electronics",p:5499,dc:0,s:15,a:{type:"earbuds",noise_cancel:"ANC",charging:"USB-C",battery:"30h",color:"black"},t:"earbuds,pro,anc,black,audio,mobile",cp:"p_phone_01,p_phone_02",fb:"p_phone_01",u:"mobile,music,calls,gym,commute",sg:"mobile-users,everyone,gym-goers",sc:97},
  {id:"p_powerbank_01",n:"20000mAh Power Bank",d:"High-capacity 20000mAh power bank with USB-C PD 30W fast charge.",c:"Electronics",p:1899,dc:5,s:25,a:{capacity:"20000mAh",fast_charge:"30W USB-C",ports:"USB-C USB-A",color:"black"},t:"powerbank,20000mah,fast-charge,black,charging",cp:"p_phone_01,p_phone_02,p_earbuds_pro",fb:"p_phone_01",u:"mobile,travel,emergency,on-the-go",sg:"mobile-users,travelers,everyone",sc:93},
  {id:"p_stand_01",n:"Aluminum Laptop Stand",d:"Adjustable aluminum laptop stand, ergonomic, foldable design.",c:"Electronics",p:899,dc:0,s:42,a:{material:"aluminum",adjustable:"yes",foldable:"yes",color:"silver"},t:"laptop-stand,aluminum,adjustable,foldable",cp:"p_laptop_01,p_laptop_02,p_laptop_03",fb:"p_laptop_01",u:"office,desk,ergonomic,study",sg:"students,professionals,home-users",sc:90},
];
