/* Smart devices, watches, bags, phones, cases */
export const rawProducts3 = [
  {id:"p_watch_01",n:"Minimalist Analog Watch",d:"Minimalist analog watch with leather strap and mineral glass face.",c:"Accessories",p:1599,dc:0,s:30,a:{type:"analog",strap:"leather",case:"silver",color:"brown"},t:"watch,analog,leather,minimalist,men,silver",cp:"p_shirt_01,p_shirt_03,p_belt_01",fb:"p_shirt_01,p_belt_01",u:"formal,office,presentation",sg:"men,professionals,students",sc:91},
  {id:"p_watch_02",n:"Chronograph Sport Watch",d:"Stainless steel chronograph sport watch, black dial, 5ATM.",c:"Accessories",p:3299,dc:10,s:15,a:{type:"chronograph",strap:"stainless-steel",case:"stainless-steel",water_resistant:"yes",color:"black"},t:"watch,chronograph,sport,stainless-steel,black",cp:"p_shirt_02,p_tshirt_01",fb:"p_shirt_02",u:"sports,outdoor,daily-wear,gym",sg:"men,youth,athletes",sc:93},
  {id:"p_watch_03",n:"Smart Fitness Tracker Watch",d:"24/7 health smartwatch, heart rate, sleep tracking, 10-day battery.",c:"Electronics",p:4999,dc:0,s:20,a:{type:"smart",health:"heart-rate-sleep",water_resistant:"5ATM",battery:"10-day",color:"black"},t:"watch,smart,fitness,tracker,black,health",cp:"p_headset_01,p_mouse_01",fb:"p_laptop_01",u:"fitness,gym,health,daily-use",sg:"fitness-enthusiasts,everyone",sc:96},
  {id:"p_bag_01",n:"Canvas Weekender Bag",d:"Large canvas weekender travel bag with multiple compartments.",c:"Accessories",p:2499,dc:0,s:0,a:{color:"tan",material:"canvas",size:"weekender"},t:"bag,trip,weekender,canvas,tan,travel",cp:"p_cloth_01,p_cloth_02",fb:"p_cloth_01",u:"travel,weekend,outdoor",sg:"travelers,everyone,youth",sc:87},
  {id:"p_bag_02",n:"Leather Satchel Handbag",d:"Elegant genuine leather satchel with interior pockets.",c:"Accessories",p:3299,dc:15,s:12,a:{color:"black",material:"genuine-leather",size:"satchel"},t:"bag,handbag,satchel,leather,black,women",cp:"p_shirt_05,p_watch_01",fb:"p_shirt_05,p_watch_01",u:"office,work,formal,elegant",sg:"women,professionals,students",sc:92},
  {id:"p_bag_03",n:"Sports Duffle Bag",d:"Heavy-duty sports duffle bag, water-resistant, multiple pockets.",c:"Accessories",p:1299,dc:0,s:28,a:{color:"black",material:"polyester",size:"large"},t:"bag,duffel,sports,black,water-resistant",cp:"p_headset_01,p_mouse_01",fb:"p_cloth_01",u:"gym,sports,travel,daily-use",sg:"athletes,youth,everyone",sc:88},
  {id:"p_phone_01",n:"SmartPhone X Pro",d:"6.7in flagship phone: Snapdragon 8 Gen 3, 12GB RAM, 256GB, 50MP.",c:"Electronics",p:74999,dc:0,s:18,a:{brand:"SmartPhone",screen:"6.7-inch",processor:"Snapdragon 8 Gen3",ram:"12GB",storage:"256GB",color:"black",g5:"yes"},t:"phone,smartphone,5g,black,camera",cp:"p_headset_02,p_laptop_bag_01,p_mouse_01",fb:"p_headset_02,p_laptop_bag_01",u:"mobile,communication,photography",sg:"everyone,mobile-users",sc:97},
  {id:"p_phone_02",n:"Budget SmartPhone Plus",d:"6.5in budget phone: MediaTek Dimensity 700, 6GB, 128GB, 50MP.",c:"Electronics",p:18999,dc:10,s:35,a:{brand:"BudgetPhone",screen:"6.5-inch",processor:"MediaTek 700",ram:"6GB",storage:"128GB",color:"blue",g5:"yes"},t:"phone,budget,smartphone,blue,5g",cp:"p_headset_01,p_laptop_bag_01,p_cover_01",fb:"p_headset_01,p_cover_01",u:"mobile,student,basic",sg:"students,budget-buyers",sc:95},
  {id:"p_cover_01",n:"Silicone Shockproof Case",d:"Ultra-thin silicone case with shock-absorbing corners.",c:"Electronics",p:499,dc:0,s:80,a:{material:"silicone",protection:"shockproof",color:"clear",slim:"yes"},t:"phone,case,cover,silicone,shockproof,clear",cp:"p_phone_01,p_phone_02",fb:"p_phone_02,p_headset_01",u:"protection,daily-use",sg:"everyone,phone-users",sc:88},
  {id:"p_cover_02",n:"Rugged Armor Phone Case",d:"Military-grade rugged case with dual-layer protection.",c:"Electronics",p:899,dc:5,s:45,a:{material:"tpu-pc-hybrid",protection:"military-grade",color:"black"},t:"phone,case,cover,rugged,armor,black",cp:"p_phone_01,p_phone_02",fb:"p_phone_01",u:"protection,outdoor,heavy-duty",sg:"outdoor-users,everyone",sc:91},
  {id:"p_cloth_02",n:"Floral Print Pillow Covers",d:"Set of 2 floral print pillow covers, soft and comfortable.",c:"Home & Kitchen",p:599,dc:10,s:45,a:{color:"multicolor",material:"polyester-cotton",size:"18x18-inch"},t:"pillow-cover,floral,home,decor,cushion",cp:"p_cloth_01,p_bag_01",fb:"p_cloth_01",u:"bedroom,sofa,living-room,decor",sg:"home-users,everyone",sc:84},
];
