/* Products Part 4: Mice, keyboards, mousepad, headsets */
export const rawProducts2b = [
  {id:"p_mouse_01",n:"Wireless Optical Mouse",d:"Ergonomic wireless optical mouse with 2.4GHz receiver.",c:"Electronics",p:799,dc:0,s:60,a:{interface:"wireless",sensor:"optical",buttons:"6",color:"black"},t:"mouse,wireless,optical,black,computer",cp:"p_laptop_01,p_laptop_02,p_laptop_04,p_laptop_05",fb:"p_laptop_01,p_keyboard_01",u:"office,gaming,home,student",sg:"everyone,professionals,gamers",sc:92},
  {id:"p_mouse_02",n:"Bluetooth Trackball Mouse",d:"Precision trackball mouse with Bluetooth 5.0, multi-device.",c:"Electronics",p:1599,dc:0,s:25,a:{interface:"bluetooth",sensor:"trackball",buttons:"4",color:"silver"},t:"mouse,bluetooth,trackball,silver,premium",cp:"p_laptop_03,p_laptop_01",fb:"p_laptop_03,p_keyboard_02",u:"office,professional,creative",sg:"professionals,creatives",sc:95},
  {id:"p_keyboard_01",n:"Mechanical Gaming Keyboard",d:"RGB mechanical gaming keyboard, blue switches, full-size.",c:"Electronics",p:2499,dc:10,s:22,a:{interface:"wired",switch:"blue",layout:"full-size",rgb:"yes",color:"black"},t:"keyboard,mechanical,gaming,rgb,black",cp:"p_laptop_01,p_laptop_02,p_laptop_04",fb:"p_laptop_01,p_mouse_01",u:"gaming,office,streaming,coding",sg:"gamers,youth,professionals",sc:94},
  {id:"p_keyboard_02",n:"Slim Wireless Keyboard",d:"Ultra-slim wireless keyboard, scissor keys, tenkeyless.",c:"Electronics",p:1899,dc:0,s:30,a:{interface:"wireless",switch:"scissor",layout:"tenkeyless",color:"silver"},t:"keyboard,wireless,slim,silver,quiet",cp:"p_laptop_03,p_laptop_01,p_laptop_05",fb:"p_laptop_03,p_mouse_02",u:"office,professional,home",sg:"professionals,home-users",sc:93},
  {id:"p_mousepad_01",n:"Extended Gaming Mouse Pad",d:"Large extended gaming mouse pad, non-slip rubber base.",c:"Electronics",p:499,dc:0,s:55,a:{size:"extended",color:"black",material:"micro-weave"},t:"mousepad,gaming,extended,black",cp:"p_mouse_01,p_keyboard_01",fb:"p_mouse_01,p_laptop_01",u:"gaming,office,desk-setup",sg:"gamers,professionals",sc:89},
  {id:"p_headset_01",n:"Over-Ear Gaming Headset",d:"50mm drivers, over-ear, detachable noise-canceling mic, RGB.",c:"Electronics",p:2999,dc:0,s:18,a:{type:"over-ear",drivers:"50mm",mic:"detachable",color:"black",rgb:"yes"},t:"headset,gaming,over-ear,black,rgb,audio",cp:"p_laptop_01,p_laptop_02,p_laptop_04",fb:"p_laptop_01,p_mouse_01",u:"gaming,streaming,office,calls",sg:"gamers,streamers,professionals",sc:93},
  {id:"p_headset_02",n:"True Wireless Earbuds",d:"Compact true wireless earbuds with ANC and spatial audio.",c:"Electronics",p:3999,dc:15,s:0,a:{type:"earbuds",noise_cancel:"ANC",charging:"USB-C",battery:"24h",color:"white"},t:"earbuds,truly-wireless,anc,white,audio",cp:"p_phone_01,p_phone_02",fb:"p_phone_01",u:"mobile,music,calls,commute",sg:"mobile-users,everyone",sc:94},
  {id:"p_headset_03",n:"Studio Monitor Headphones",d:"Professional closed-back studio headphones, 40mm drivers.",c:"Electronics",p:5999,dc:0,s:12,a:{type:"over-ear",drivers:"40mm",tuning:"studio-flat",color:"black",impedance:"32ohm"},t:"headphones,studio,premium,black,audio",cp:"p_laptop_03,p_laptop_05,p_keyboard_02",fb:"p_laptop_03",u:"studio,production,music,mixing",sg:"creatives,professionals,audiophiles",sc:96},
  {id:"p_phone_01",n:"SmartPhone X Pro",d:"6.7in flagship phone: Snapdragon 8 Gen3, 12GB, 256GB, 50MP.",c:"Electronics",p:74999,dc:0,s:18,a:{brand:"SmartPhone",screen:"6.7-inch",processor:"Snapdragon 8 Gen3",ram:"12GB",storage:"256GB",color:"black",g5:"yes"},t:"phone,smartphone,5g,black,camera",cp:"p_headset_02,p_laptop_bag_01,p_mouse_01",fb:"p_headset_02,p_laptop_bag_01",u:"mobile,communication,photography",sg:"everyone,mobile-users",sc:97},
];
