/* Products Part 2: Casual wear, belts */
export const rawProducts1b = [
  {id:"p_jeans_01",n:"Slim Fit Blue Jeans",d:"Dark blue slim-fit jeans with stretch cotton, reinforced stitching.",c:"Clothing",p:1199,dc:20,s:33,a:{color:"blue",material:"cotton-stretch",fit:"slim"},t:"jeans,blue,slim,casual,men,pants",cp:"p_shirt_04,p_tshirt_01",fb:"p_tshirt_01,p_belt_02",u:"casual,daily-wear,friends-gathering,college",sg:"men,youth,students",sc:94},
  {id:"p_jeans_02",n:"Black Skinny Jeans",d:"Jet black skinny-fit jeans with high-stretch fabric.",c:"Clothing",p:1499,dc:0,s:14,a:{color:"black",material:"cotton-spandex",fit:"skinny"},t:"jeans,black,skinny,casual,men,pants",cp:"p_shirt_05,p_tshirt_01",fb:"p_tshirt_01",u:"night-out,daily-wear,party,college",sg:"men,youth,students",sc:92},
  {id:"p_chino_01",n:"Beige Stretch Chinos",d:"Comfortable beige stretch chinos with slim tapered fit.",c:"Clothing",p:999,dc:0,s:27,a:{color:"beige",material:"cotton-polyester",fit:"slim"},t:"chinos,beige,casual,men,pants",cp:"p_shirt_04,p_tshirt_01,p_belt_02",fb:"p_tshirt_01,p_belt_02",u:"casual,daily-wear,college",sg:"men,youth,students",sc:89},
  {id:"p_chino_02",n:"Olive Green Chino Pants",d:"Olive green chino pants with modern slim fit.",c:"Clothing",p:899,dc:10,s:19,a:{color:"olive",material:"cotton-polyester",fit:"slim"},t:"chinos,olive,casual,men,pants",cp:"p_tshirt_01,p_shirt_04",fb:"p_tshirt_01",u:"casual,daily-wear,college,outing",sg:"men,youth,students",sc:85},
  {id:"p_tshirt_01",n:"White Cotton T-Shirt",d:"Classic white cotton t-shirt with regular fit.",c:"Clothing",p:499,dc:0,s:50,a:{color:"white",material:"cotton",fit:"regular"},t:"tshirt,white,casual,men,essential",cp:"p_jeans_01,p_chino_01",fb:"p_jeans_01",u:"casual,daily-wear,layering,college",sg:"men,youth,students,everyone",sc:96},
  {id:"p_tshirt_03",n:"Grey Crew Neck T-Shirt",d:"Soft grey crew neck t-shirt from combed cotton.",c:"Clothing",p:549,dc:5,s:38,a:{color:"grey",material:"cotton",fit:"regular"},t:"tshirt,grey,casual,men,basic",cp:"p_jeans_01,p_chino_01",fb:"p_jeans_01",u:"casual,daily-wear,layering,college",sg:"men,youth,students",sc:93},
  {id:"p_belt_01",n:"Leather Formal Belt",d:"Premium genuine leather belt with polished silver buckle.",c:"Accessories",p:399,dc:0,s:40,a:{color:"black",material:"genuine-leather",size:"adjustable"},t:"belt,leather,formal,accessory,men,black",cp:"p_shirt_01,p_shirt_02,p_trouser_01",fb:"p_shirt_01,p_trouser_01",u:"formal,office,presentation",sg:"men,professionals,students",sc:90},
  {id:"p_belt_02",n:"Brown Leather Casual Belt",d:"Handcrafted brown leather belt with vintage bronze buckle.",c:"Accessories",p:349,dc:0,s:22,a:{color:"brown",material:"genuine-leather",size:"adjustable"},t:"belt,leather,brown,casual,accessory",cp:"p_jeans_01,p_chino_01",fb:"p_chino_01",u:"casual,daily-wear,friends-gathering",sg:"men,youth,casual",sc:86},
  {id:"p_tshirt_02",n:"Black Graphic Tee",d:"Stylish black graphic t-shirt with contemporary design.",c:"Clothing",p:699,dc:0,s:0,a:{color:"black",material:"cotton",fit:"regular"},t:"tshirt,black,graphic,casual,men,streetwear",cp:"p_jeans_02,p_jeans_01",fb:"p_jeans_02",u:"casual,night-out,party",sg:"men,youth,students",sc:90},
];
