/* Products Part 1: Formal shirts, trousers, ties */
export const rawProducts1a = [
  {id:"p_shirt_01",n:"Formal Cotton Shirt",d:"Premium white cotton formal shirt with slim fit, spread collar, and button placket.",c:"Clothing",p:1299,dc:10,s:25,a:{color:"white",material:"cotton",fit:"slim",occasion:"formal"},t:"shirt,formal,white,office,men",cp:"p_trouser_01,p_belt_01",fb:"p_trouser_01,p_belt_01",u:"office,presentation,interview,formal",sg:"men,professionals,students",sc:96},
  {id:"p_shirt_02",n:"Black Formal Shirt",d:"Sophisticated black formal shirt in premium cotton with spread collar.",c:"Clothing",p:1399,dc:5,s:0,a:{color:"black",material:"cotton",fit:"regular",occasion:"formal"},t:"shirt,formal,black,office,men",cp:"p_trouser_01",fb:"p_trouser_01,p_tie_01",u:"evening,presentation,formal,interview",sg:"men,professionals",sc:94},
  {id:"p_shirt_03",n:"Navy Blue Formal Shirt",d:"Navy blue formal shirt from soft cotton with tailored fit.",c:"Clothing",p:1249,dc:0,s:18,a:{color:"navy",material:"cotton",fit:"tailored",occasion:"formal"},t:"shirt,formal,navy,office,men",cp:"p_trouser_01,p_tie_01",fb:"p_trouser_01",u:"meeting,office,presentation,business",sg:"men,professionals,students",sc:92},
  {id:"p_shirt_04",n:"Check Print Formal Shirt",d:"Modern check-patterned sky blue formal shirt with subtle plaid design.",c:"Clothing",p:1199,dc:15,s:12,a:{color:"blue",material:"cotton",fit:"regular",occasion:"casual-formal"},t:"shirt,check,blue,casual,formal,men",cp:"p_trouser_01",fb:"p_belt_01",u:"casual,office,daily-wear",sg:"men,youth,casual",sc:88},
  {id:"p_shirt_05",n:"Pink Formal Shirt",d:"Contemporary pale pink formal shirt in cotton with classic cut.",c:"Clothing",p:1449,dc:0,s:8,a:{color:"pink",material:"cotton",fit:"slim",occasion:"business-casual"},t:"shirt,pink,formal,casual,men",cp:"p_trouser_01,p_tie_01",fb:"p_tie_01",u:"business-casual,office,meeting",sg:"men,youth,professionals",sc:89},
  {id:"p_trouser_01",n:"Regular Fit Formal Trouser",d:"Classic beige formal trousers with regular fit and flat front.",c:"Clothing",p:1499,dc:0,s:30,a:{color:"beige",material:"polyester-cotton",fit:"regular",occasion:"formal"},t:"trouser,formal,beige,pants,men",cp:"p_shirt_01,p_shirt_02",fb:"p_shirt_01,p_belt_01",u:"office,presentation,formal,interview",sg:"men,professionals,students",sc:91},
  {id:"p_trouser_02",n:"Slim Fit Black Trouser",d:"Sleek black slim-fit trousers with modern cut.",c:"Clothing",p:1599,dc:5,s:0,a:{color:"black",material:"polyester",fit:"slim",occasion:"formal"},t:"trouser,black,slim,pants,men,formal",cp:"p_shirt_02",fb:"p_shirt_02",u:"evening,presentation,formal,interview",sg:"men,professionals",sc:87},
  {id:"p_trouser_03",n:"Navy Wool Blend Trouser",d:"Premium navy blue wool blend trousers with pleated detailing.",c:"Clothing",p:1899,dc:10,s:15,a:{color:"navy",material:"wool-blend",fit:"regular",occasion:"formal"},t:"trouser,navy,wool,pants,men,formal",cp:"p_shirt_03,p_shirt_01",fb:"p_belt_01,p_shirt_01",u:"office,meeting,presentation,wedding",sg:"men,professionals,seniors",sc:95},
  {id:"p_tie_01",n:"Silk Maroon Tie",d:"Luxurious silk tie in deep maroon with subtle sheen.",c:"Accessories",p:499,dc:0,s:35,a:{color:"maroon",material:"silk",width:"standard"},t:"tie,silk,maroon,formal,accessory,men",cp:"p_shirt_01,p_shirt_02",fb:"p_shirt_01,p_belt_01",u:"interview,presentation,wedding,formal",sg:"men,professionals,students",sc:91},
  {id:"p_tie_02",n:"Navy Blue Slim Tie",d:"Navy blue slim-fit tie in premium polyester with texture.",c:"Accessories",p:349,dc:5,s:28,a:{color:"navy",material:"polyester",width:"slim"},t:"tie,slim,navy,formal,accessory,men",cp:"p_shirt_03,p_shirt_04",fb:"p_shirt_03",u:"office,meeting,business-casual",sg:"men,youth,professionals",sc:87},
];
