/* Products Part 3: Laptops, laptop bags, mice, keyboards */
export const rawProducts2a = [
  {id:"p_laptop_01",n:"UltraThin Pro Laptop 14in",d:"14-inch ultrathin laptop with Intel i7, 16GB RAM, 512GB SSD.",c:"Electronics",p:74999,dc:0,s:12,a:{brand:"UltraThin",screen:"14-inch",processor:"Intel i7",ram:"16GB",storage:"512GB SSD",os:"Win11",color:"silver"},t:"laptop,ultrabook,silver,student,office",cp:"p_laptop_bag_01,p_mouse_01,p_mousepad_01,p_laptop_stand_01",fb:"p_laptop_bag_01,p_mouse_01,p_laptop_stand_01",u:"office,student,coding,gaming",sg:"students,professionals",sc:98},
  {id:"p_laptop_02",n:"Gaming Beast Pro 15.6in",d:"15.6-inch gaming laptop: AMD Ryzen 7, RTX 4060, 16GB, 1TB SSD.",c:"Electronics",p:109999,dc:5,s:8,a:{brand:"GameBeast",screen:"15.6-inch",processor:"AMD Ryzen 7",ram:"16GB",storage:"1TB SSD",gpu:"RTX 4060",os:"Win11",color:"black"},t:"laptop,gaming,amd,rtx,black",cp:"p_laptop_bag_01,p_mouse_01,p_headset_01,p_laptop_stand_01",fb:"p_laptop_bag_01,p_mouse_01,p_headset_01,p_laptop_stand_01",u:"gaming,coding,streaming",sg:"gamers,youth,students",sc:97},
  {id:"p_laptop_03",n:"MacBook Air M2 13in",d:"13-inch MacBook Air M2 chip, 8GB RAM, 256GB SSD. Featherlight.",c:"Electronics",p:94999,dc:0,s:6,a:{brand:"Apple",screen:"13-inch",processor:"Apple M2",ram:"8GB",storage:"256GB SSD",os:"macOS",color:"silver"},t:"laptop,macbook,apple,silver,creative",cp:"p_laptop_bag_02,p_mouse_02,p_laptop_stand_01",fb:"p_laptop_bag_02,p_laptop_stand_01",u:"creative,design,coding,student",sg:"creatives,students,professionals",sc:99},
  {id:"p_laptop_04",n:"BudgetEdge 15.6in Laptop",d:"Affordable 15.6-inch laptop: AMD Ryzen 5, 8GB RAM, 512GB SSD.",c:"Electronics",p:54999,dc:15,s:20,a:{brand:"BudgetEdge",screen:"15.6-inch",processor:"AMD Ryzen 5",ram:"8GB",storage:"512GB SSD",os:"Win11",color:"black"},t:"laptop,budget,amd,black,affordable",cp:"p_laptop_bag_01,p_mouse_01,p_laptop_stand_01",fb:"p_laptop_bag_01,p_mousepad_01,p_laptop_stand_01",u:"home,student,office",sg:"students,budget-buyers",sc:94},
  {id:"p_laptop_05",n:"WorkPro 14in Business Laptop",d:"14-inch business laptop: Intel i5, 16GB, 512GB SSD, TPM 2.0.",c:"Electronics",p:69999,dc:0,s:14,a:{brand:"WorkPro",screen:"14-inch",processor:"Intel i5",ram:"16GB",storage:"512GB SSD",os:"Win11 Pro",color:"black",security:"TPM 2.0"},t:"laptop,business,intel,black,office",cp:"p_laptop_bag_01,p_mouse_01,p_laptop_stand_01",fb:"p_laptop_bag_01,p_mousepad_01,p_laptop_stand_01",u:"office,business,professional",sg:"professionals,business-users",sc:96},
  {id:"p_laptop_bag_01",n:"Neoprene Laptop Sleeve 15in",d:"Water-resistant neoprene laptop sleeve, padded interior.",c:"Electronics",p:1499,dc:0,s:45,a:{color:"black",material:"neoprene",size:"15-inch"},t:"laptop-bag,sleeve,neoprene,black",cp:"p_laptop_01,p_laptop_02,p_laptop_04,p_laptop_05",fb:"p_laptop_01,p_mouse_01",u:"protection,travel,student",sg:"students,professionals",sc:91},
  {id:"p_laptop_stand_01",n:"Aluminium Laptop Stand Adjustable",d:"Ergonomic foldable aluminium laptop stand with 6 height levels & heat-dissipating design.",c:"Accessories",p:899,dc:10,s:38,a:{emoji:"🖥️",type:"laptop-stand",material:"aluminium",height_adjust:"6-level"},t:"laptop-stand,stand,aluminium,ergonomic,dock",cp:"p_laptop_01,p_laptop_02,p_laptop_04,p_laptop_05,p_glap_01,p_glap_03",fb:"p_laptop_01,p_laptop_03,p_glap_04,p_mouse_01",u:"office,study,gaming,ergonomics",sg:"students,professionals,gamers",sc:90},
  {id:"p_laptop_bag_02",n:"Premium Leather Briefcase",d:"Genuine leather laptop briefcase with multiple compartments.",c:"Electronics",p:3499,dc:10,s:18,a:{color:"brown",material:"genuine-leather",size:"13-inch"},t:"laptop-bag,briefcase,leather,brown",cp:"p_laptop_03,p_laptop_01",fb:"p_laptop_03",u:"business,professional,travel",sg:"professionals,business-users",sc:93},
  {id:"p_laptop_bag_03",n:"Student Laptop Backpack 15in",d:"Multi-compartment backpack with USB charging port.",c:"Electronics",p:1999,dc:5,s:33,a:{color:"black",material:"polyester",size:"15-inch"},t:"laptop-bag,backpack,student,black,usb",cp:"p_laptop_01,p_laptop_04,p_laptop_02",fb:"p_laptop_01,p_mouse_01,p_headset_01",u:"student,college,travel",sg:"students,college-goers",sc:95},
  {id:"p_laptop_bag_04",n:"Slim Laptop Messenger Bag",d:"Slim-profile messenger laptop bag with padded compartment.",c:"Electronics",p:1299,dc:0,s:0,a:{color:"grey",material:"polyester",size:"15-inch"},t:"laptop-bag,messenger,grey,slim",cp:"p_laptop_01,p_laptop_04",fb:"p_laptop_01,p_mouse_01",u:"student,office,travel",sg:"students,commuters",sc:90},
];
