

/* MERCHANTOS AI — Schema Definition (SQLite/PostgreSQL compatible) */
export const SCHEMA_SQL = `CREATE TABLE IF NOT EXISTS merchants (id TEXT PRIMARY KEY DEFAULT 'default_merchant', name TEXT NOT NULL, email TEXT, timezone TEXT DEFAULT 'Asia/Kolkata', currency TEXT DEFAULT 'INR', created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL, category TEXT NOT NULL, price INTEGER NOT NULL, discount_percent INTEGER DEFAULT 0, stock INTEGER NOT NULL DEFAULT 0, attributes_json TEXT, variants_json TEXT, tags TEXT, compatible_products TEXT, frequently_bought_together TEXT, target_use_cases TEXT, customer_segments TEXT, merchant_rule_json TEXT, ai_readiness_score REAL DEFAULT 0, is_active INTEGER DEFAULT 1, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS customers (id TEXT PRIMARY KEY, name TEXT, email TEXT, phone TEXT, preferences_json TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, customer_id TEXT, started_at TEXT DEFAULT (datetime('now')), last_active TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS cart_sessions (session_id TEXT PRIMARY KEY, items_json TEXT, total REAL DEFAULT 0, currency TEXT DEFAULT 'INR', updated_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, session_id TEXT, customer_name TEXT, total_amount REAL NOT NULL, currency TEXT DEFAULT 'INR', status TEXT DEFAULT 'pending', razorpay_order_id TEXT, razorpay_payment_id TEXT, is_ai_assisted INTEGER DEFAULT 0, upsell_applied INTEGER DEFAULT 0, cross_sell_applied INTEGER DEFAULT 0, ai_confidence REAL, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS order_items (id TEXT PRIMARY KEY, order_id TEXT NOT NULL, product_id TEXT NOT NULL, product_name TEXT NOT NULL, quantity INTEGER NOT NULL, price REAL NOT NULL, variant_id TEXT, item_type TEXT DEFAULT 'primary', FOREIGN KEY (order_id) REFERENCES orders(id));
CREATE TABLE IF NOT EXISTS payments (id TEXT PRIMARY KEY, order_id TEXT NOT NULL, razorpay_payment_id TEXT, amount REAL NOT NULL, currency TEXT DEFAULT 'INR', status TEXT DEFAULT 'pending', method TEXT, created_at TEXT DEFAULT (datetime('now')), verified_at TEXT, FOREIGN KEY (order_id) REFERENCES orders(id));
CREATE TABLE IF NOT EXISTS audit_events (id TEXT PRIMARY KEY, order_id TEXT, session_id TEXT, actor TEXT NOT NULL, action TEXT NOT NULL, reason TEXT, status TEXT NOT NULL, details_json TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS ai_actions (id TEXT PRIMARY KEY, session_id TEXT, order_id TEXT, action_type TEXT NOT NULL, input_json TEXT, output_json TEXT, confidence REAL, approved INTEGER DEFAULT 0, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS abandoned_carts (id TEXT PRIMARY KEY, session_id TEXT, items_json TEXT, total REAL, reason TEXT, created_at TEXT DEFAULT (datetime('now')), recovery_sent INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS policies (id TEXT PRIMARY KEY, key TEXT NOT NULL, value TEXT NOT NULL, description TEXT, category TEXT NOT NULL, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS recommendations (id TEXT PRIMARY KEY, session_id TEXT, product_id TEXT, product_name TEXT, score REAL, reason TEXT, recommendation_type TEXT, accepted INTEGER DEFAULT 0, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS revenue_events (id TEXT PRIMARY KEY, order_id TEXT, amount REAL, revenue_type TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS intent_trends (id TEXT PRIMARY KEY, query TEXT, parsed_intent TEXT, category TEXT, budget REAL, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS campaigns (id TEXT PRIMARY KEY, name TEXT, description TEXT, target_segment TEXT, action TEXT, status TEXT DEFAULT 'draft', metrics_json TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE INDEX IF NOT EXISTS idx_orders_created ON orders(created_at); CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_events(created_at); CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status); CREATE INDEX IF NOT EXISTS idx_products_category ON products(category); CREATE INDEX IF NOT EXISTS idx_audit_session ON audit_events(session_id); CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status); CREATE INDEX IF NOT EXISTS idx_intent_trends_category ON intent_trends(category, created_at);`;